import { Course, Chapter, Section, ExamQuestion, MultipleChoiceQuestion, TrueFalseQuestion, FillBlankQuestion, CodeOrderQuestion, MatchPairsQuestion, Project } from "../types";
import { pythonChapters1to10 } from "./chapters-1-10";
import { pythonChapters11to30 } from "./chapters-11-30";
import { pythonChapters31to40 } from "./chapters-31-40";

const pythonChapters: Chapter[] = [
  // Chapters 1-10: hand-crafted quality content
  ...pythonChapters1to10,
  // Chapters 11-30: hand-crafted quality content
  ...pythonChapters11to30,
  // Chapters 31-40: advanced Python features
  ...pythonChapters31to40,
];

const pythonProjects: Project[] = [
  {
    id: "py-hello",
    courseId: "python",
    title: "Hello World",
    description: "Write and run your first Python program. Learn basic syntax, the print() function, and how to run Python scripts.",
    difficulty: 1,
    order: 1,
    learningObjectives: ["Install Python and run a script","Use print() for output","Understand basic Python syntax"],
    requirements: ["Print 'Hello, World!' to the console","Print your name and age on separate lines","Add a comment explaining each line"],
    hints: ["print() displays text to the console","Comments start with #","Strings go in quotes (single or double)"],
    expectedConcepts: ["python-introduction","python-getting-started","python-syntax","python-comments"],
    estimatedMinutes: 10,
    xpReward: 15,
  },
  {
    id: "py-bmi",
    courseId: "python",
    title: "BMI Calculator",
    description: "Calculate Body Mass Index from user input — practicing functions, math operations, and user input.",
    difficulty: 1,
    order: 2,
    learningObjectives: ["Define and call functions","Use input() to accept user input","Perform arithmetic operations"],
    requirements: ["Ask for weight (kg) and height (m)","Calculate BMI = weight / height²","Display BMI category: Underweight (<18.5), Normal, Overweight (25-30), Obese (>30)"],
    hints: ["def calculate_bmi(weight, height):","Use float(input()) for numeric input","Use if/elif/else for BMI categories"],
    expectedConcepts: ["python-functions","python-math","python-if-else","python-user-input"],
    estimatedMinutes: 20,
    xpReward: 25,
  },
  {
    id: "py-number-game",
    courseId: "python",
    title: "Number Guessing Game",
    description: "The computer picks a random number — guess it with hints. Learn loops, conditionals, and the random module.",
    difficulty: 1,
    order: 3,
    learningObjectives: ["Use the random module","Implement game loops with while","Provide feedback with if/elif/else"],
    requirements: ["Random number between 1-100","Player enters guesses","Hint: too high / too low","Show attempt count","Max 10 attempts"],
    hints: ["import random, target = random.randint(1, 100)","while True for game loop with break","int(input()) to read guess"],
    expectedConcepts: ["python-random","python-while","python-if-else","python-functions"],
    estimatedMinutes: 25,
    xpReward: 30,
  },
  {
    id: "py-word-count",
    courseId: "python",
    title: "Word Counter",
    description: "Count words, characters, and sentences in user-provided text — mastering string methods.",
    difficulty: 1,
    order: 4,
    learningObjectives: ["Use string methods for text analysis","Split and join strings","Count occurrences"],
    requirements: ["Accept multi-line text input","Count: words, characters (with/without spaces), sentences","Display results in a formatted output"],
    hints: ["Use .split() to get words","len() for counting","Count sentences by splitting on '.', '!', '?'"],
    expectedConcepts: ["python-strings","python-string-methods","python-functions"],
    estimatedMinutes: 20,
    xpReward: 25,
  },
  {
    id: "py-password-gen",
    courseId: "python",
    title: "Password Generator",
    description: "Generate secure random passwords with customizable options — strings, randomness, and lists.",
    difficulty: 2,
    order: 5,
    learningObjectives: ["Random selection from character pools","Build strings with loops","Handle user preferences"],
    requirements: ["Choose password length (8-32)","Options for uppercase, lowercase, digits, symbols","Generate and display the password","Generate multiple passwords at once"],
    hints: ["import string for ascii_letters, digits, punctuation","random.choice() picks one random character","List comprehension: [random.choice(pool) for _ in range(n)]"],
    expectedConcepts: ["python-random","python-strings","python-string-methods","python-loops","python-modules"],
    estimatedMinutes: 25,
    xpReward: 35,
  },
  {
    id: "py-hangman",
    courseId: "python",
    title: "Hangman Game",
    description: "Build the classic word-guessing game Hangman — lists, strings, and game loop logic.",
    difficulty: 2,
    order: 6,
    learningObjectives: ["Work with lists and string manipulation","Implement game state tracking","Design a simple text-based UI"],
    requirements: ["Random word from a predefined list","Display blanks for unguessed letters (_ _ _ _ _)","Show guessed letters and remaining attempts","ASCII art showing the hangman progress","Win/lose detection"],
    hints: ["Use list('word') to work with individual letters","Track guessed: set() stores guessed letters","Display: ' '.join('_' if l not in guessed else l for l in word)"],
    expectedConcepts: ["python-lists","python-strings","python-random","python-functions","python-loops"],
    estimatedMinutes: 40,
    xpReward: 45,
  },
  {
    id: "py-todo-file",
    courseId: "python",
    title: "To-Do List Manager",
    description: "Build a persistent to-do list using file I/O — reading, writing, and managing data in files.",
    difficulty: 2,
    order: 7,
    learningObjectives: ["Read and write text files","Parse structured data","Build a menu-driven CLI application"],
    requirements: ["Add, view, complete, and delete tasks","Tasks persist in a text file","Numbered menu with options","Save on every change"],
    hints: ["Store tasks as lines in a .txt file","with open('todos.txt', 'r') as f: for reading","Use .strip() to clean lines","Each line: task_number|task_text|completed"],
    expectedConcepts: ["python-file-read","python-file-write","python-functions","python-loops"],
    estimatedMinutes: 35,
    xpReward: 40,
  },
  {
    id: "py-mad-libs",
    courseId: "python",
    title: "Mad Libs Generator",
    description: "Create a Mad Libs word game — collect words from the user and insert them into a story template.",
    difficulty: 1,
    order: 8,
    learningObjectives: ["Collect and store user input","Use string formatting effectively","Build a template-based story generator"],
    requirements: ["Ask for words (noun, verb, adjective, etc.)","Insert words into a story template","Display the complete funny story","Allow replay with different words"],
    hints: ["Use f-strings for template: f'The {adj} {noun} {verb}.'","Store user inputs in a dict","Create multiple story templates"],
    expectedConcepts: ["python-strings","python-string-methods","python-functions","python-dictionaries"],
    estimatedMinutes: 20,
    xpReward: 25,
  },
  {
    id: "py-rps",
    courseId: "python",
    title: "Rock Paper Scissors",
    description: "Play Rock Paper Scissors against the computer — conditionals, random choices, and score tracking.",
    difficulty: 1,
    order: 9,
    learningObjectives: ["Use random selection","Implement game rules with conditionals","Track scores across rounds"],
    requirements: ["Player picks Rock, Paper, or Scissors","Computer picks randomly","Determine winner each round","Best of 5 rounds","Display final winner"],
    hints: ["Use random.choice(['rock', 'paper', 'scissors'])","Create a dict mapping choice → beats","Use while rounds < 5 for the game loop"],
    expectedConcepts: ["python-if-else","python-random","python-while","python-dictionaries"],
    estimatedMinutes: 25,
    xpReward: 30,
  },
  {
    id: "py-caesar",
    courseId: "python",
    title: "Caesar Cipher",
    description: "Implement the Caesar cipher encryption and decryption — string manipulation and algorithmic thinking.",
    difficulty: 2,
    order: 10,
    learningObjectives: ["Implement a substitution cipher","Work with character codes (ord/char)","Handle wrap-around in a circular alphabet"],
    requirements: ["Input: message and shift value","Encrypt: shift each letter by the shift amount","Decrypt: reverse the shift","Preserve case and non-letter characters","Brute-force decrypt by trying all 26 shifts"],
    hints: ["ord('a') → 97, chr(97) → 'a'","Shift: (ord(c) - 97 + shift) % 26 + 97","Preserve case by checking .isupper() / .islower()"],
    expectedConcepts: ["python-strings","python-string-methods","python-loops","python-functions"],
    estimatedMinutes: 30,
    xpReward: 40,
  },
  {
    id: "py-quiz",
    courseId: "python",
    title: "Quiz Game",
    description: "Build a multiple-choice quiz game using dictionaries and lists — data-driven programming.",
    difficulty: 2,
    order: 11,
    learningObjectives: ["Structure quiz data with dicts and lists","Implement scoring and feedback","Randomize question order"],
    requirements: ["10+ questions with 4 options each","Shuffle question order each game","Display score after each answer","Show final score and percentage","Option to replay"],
    hints: ["questions = [{ 'q': '...', 'options': [...], 'correct': 2 }]","random.shuffle(questions) for order","Use enumerate() for numbered options"],
    expectedConcepts: ["python-dictionaries","python-lists","python-random","python-functions","python-loops"],
    estimatedMinutes: 35,
    xpReward: 45,
  },
  {
    id: "py-contacts",
    courseId: "python",
    title: "Contact Book",
    description: "Build a contact book that saves to JSON — CRUD operations and data serialization.",
    difficulty: 2,
    order: 12,
    learningObjectives: ["Implement CRUD operations","Serialize/deserialize with JSON","Build a user-friendly CLI"],
    requirements: ["Add contacts (name, phone, email)","View all contacts as a list","Search contacts by name","Update existing contacts","Delete contacts","Persist to contacts.json"],
    hints: ["Use json.dump() / json.load() for persistence","Each contact: { 'id': 1, 'name': '...', 'phone': '...', 'email': '...' }","Use .lower() for case-insensitive search"],
    expectedConcepts: ["python-json","python-file-read","python-file-write","python-dictionaries","python-functions"],
    estimatedMinutes: 40,
    xpReward: 50,
  },
  {
    id: "py-weather-cli",
    courseId: "python",
    title: "Weather CLI",
    description: "Fetch real weather data from a public API and display it in the terminal — learning HTTP requests.",
    difficulty: 3,
    order: 13,
    learningObjectives: ["Make HTTP requests with the requests library","Parse JSON responses","Handle API errors gracefully"],
    requirements: ["Input a city name","Fetch current weather from OpenWeatherMap API","Display temperature, conditions, humidity, wind","Handle network errors and invalid cities"],
    hints: ["pip install requests","Use requests.get(url).json()","Store API key in an environment variable","Use try/except for connection errors"],
    expectedConcepts: ["python-modules","python-pip","python-json","python-exceptions","python-functions"],
    estimatedMinutes: 45,
    xpReward: 60,
  },
  {
    id: "py-expense-tracker",
    courseId: "python",
    title: "Expense Tracker",
    description: "Track expenses and generate summaries — CSV file handling and data analysis basics.",
    difficulty: 2,
    order: 14,
    learningObjectives: ["Read/write CSV files","Calculate summaries with aggregation","Display formatted reports"],
    requirements: ["Add expenses (date, category, amount, description)","View all expenses","Filter by category","Show totals per category and overall","Export summary as CSV"],
    hints: ["import csv — use csv.writer() and csv.reader()","Store expenses as a list of dicts","Use collections.defaultdict for category sums"],
    expectedConcepts: ["python-csv","python-dictionaries","python-functions","python-exceptions"],
    estimatedMinutes: 40,
    xpReward: 50,
  },
  {
    id: "py-web-scraper",
    courseId: "python",
    title: "Web Scraper",
    description: "Scrape and extract data from web pages — learning BeautifulSoup and HTML parsing.",
    difficulty: 3,
    order: 15,
    learningObjectives: ["Send HTTP requests and parse HTML","Extract structured data from web pages","Handle pagination and rate limiting"],
    requirements: ["Fetch web page content with requests","Parse HTML with BeautifulSoup","Extract specific elements (titles, links, prices)","Save results to a CSV file","Handle errors for missing elements"],
    hints: ["pip install beautifulsoup4 requests","Use soup.find_all('tag', class_='cls') for selection","Save extracted data as list of dicts","Add time.sleep(1) between requests to be polite"],
    expectedConcepts: ["python-modules","python-pip","python-csv","python-loops","python-functions"],
    estimatedMinutes: 50,
    xpReward: 65,
  },
  {
    id: "py-tic-tac-toe",
    courseId: "python",
    title: "Tic-Tac-Toe (CLI)",
    description: "Build Tic-Tac-Toe for the terminal — 2D arrays, game logic, and simple AI opponent.",
    difficulty: 2,
    order: 16,
    learningObjectives: ["Work with 2D arrays/list of lists","Implement win-condition checking","Build a simple AI"],
    requirements: ["3×3 board displayed in terminal","Two-player mode","AI opponent mode","Win/draw detection","Play again option"],
    hints: ["Board: [[' ' for _ in range(3)] for _ in range(3)]","Check rows, columns, diagonals for 3 in a row","Simple AI: pick random empty cell as fallback"],
    expectedConcepts: ["python-lists","python-loops","python-functions","python-random"],
    estimatedMinutes: 40,
    xpReward: 50,
  },
  {
    id: "py-markdown-html",
    courseId: "python",
    title: "Markdown to HTML Converter",
    description: "Convert Markdown text to HTML — a practical exercise in text parsing and regex.",
    difficulty: 3,
    order: 17,
    learningObjectives: ["Use regular expressions for pattern matching","Implement a text-to-HTML pipeline","Output valid HTML"],
    requirements: ["Read Markdown from a file or input","Convert: # heading, **bold**, *italic*, - lists, [links]()","Output valid HTML","Save output to .html file"],
    hints: ["import re for regex substitutions","r'^#{1,6} (.*)' matches headings","re.sub(pattern, replacement, text) for replacement"],
    expectedConcepts: ["python-regex","python-strings","python-string-methods","python-file-read","python-file-write"],
    estimatedMinutes: 45,
    xpReward: 55,
  },
  {
    id: "py-snake-game",
    courseId: "python",
    title: "Snake Game",
    description: "Build the classic Snake game using Pygame — game loops, collision detection, and event handling.",
    difficulty: 3,
    order: 18,
    learningObjectives: ["Use Pygame for graphics and input","Implement a game loop with fixed FPS","Handle collision detection"],
    requirements: ["Snake moves continuously in 4 directions","Arrow keys change direction","Food spawns randomly — eating grows the snake","Game over on wall/self collision","Score display"],
    hints: ["pip install pygame","Snake as list of (x, y) segments","Game loop: handle_input → update → draw","Use pygame.time.Clock().tick(10) for speed"],
    expectedConcepts: ["python-modules","python-pip","python-loops","python-classes","python-functions"],
    estimatedMinutes: 60,
    xpReward: 80,
  },
  {
    id: "py-url-shortener",
    courseId: "python",
    title: "URL Shortener (Flask)",
    description: "Build a URL shortener web app with Flask — web development, routing, and database storage.",
    difficulty: 3,
    order: 19,
    learningObjectives: ["Create a Flask web application","Handle HTTP routes (GET/POST)","Use SQLite for persistent storage"],
    requirements: ["Home page with input for long URL","Generate a short, unique code for each URL","Redirect short URL to the original","Track visit count for each link","List all shortened URLs"],
    hints: ["pip install flask","Use string.ascii_letters + digits for short codes","import sqlite3 for database","Store URLs in a table: id, original, short_code, visits, created"],
    expectedConcepts: ["python-modules","python-functions","python-sqlite","python-json"],
    estimatedMinutes: 60,
    xpReward: 75,
  },
  {
    id: "py-password-manager",
    courseId: "python",
    title: "Password Manager",
    description: "Build a secure password manager with encryption — security, hashing, and file I/O.",
    difficulty: 3,
    order: 20,
    learningObjectives: ["Hash passwords with hashlib","Encrypt/decrypt data with cryptography","Build a master-password-protected vault"],
    requirements: ["Master password authentication (SHA-256 hashed)","Add service credentials (service, username, password)","View saved credentials","Copy password to clipboard","Encrypt stored passwords"],
    hints: ["import hashlib; hashlib.sha256(pw.encode()).hexdigest()","from cryptography.fernet import Fernet for encryption","Store vault as encrypted JSON file","Use getpass for hidden password entry"],
    expectedConcepts: ["python-hashlib","python-json","python-functions","python-file-read","python-file-write"],
    estimatedMinutes: 55,
    xpReward: 70,
  },
  {
    id: "py-data-analyzer",
    courseId: "python",
    title: "Data Analyzer",
    description: "Analyze a real dataset using Pandas and create visualizations with Matplotlib — data science foundations.",
    difficulty: 3,
    order: 21,
    learningObjectives: ["Load and explore datasets with Pandas","Filter, group, and aggregate data","Create visualizations with Matplotlib"],
    requirements: ["Load a CSV dataset (e.g., Titanic, Iris, or custom)","Display basic statistics (mean, median, count)","Filter data by conditions","Create at least 2 charts (bar, scatter, histogram)","Export analysis summary"],
    hints: ["pip install pandas matplotlib","df = pd.read_csv('data.csv')","df.describe() for statistics","plt.bar(), plt.scatter(), plt.hist() for charts"],
    expectedConcepts: ["python-modules","python-pip","python-functions","python-csv","python-pandas"],
    estimatedMinutes: 60,
    xpReward: 75,
  },
  {
    id: "py-rest-client",
    courseId: "python",
    title: "REST API Client",
    description: "Build a CLI tool that interacts with REST APIs — making requests, handling responses, and formatting output.",
    difficulty: 3,
    order: 22,
    learningObjectives: ["Use the requests library for HTTP methods","Handle JSON request/response bodies","Build a practical command-line tool"],
    requirements: ["GET, POST, PUT, DELETE operations","Set headers and body in requests","Display formatted JSON responses","Save responses to files"],
    hints: ["import requests; resp = requests.get(url)","resp.json() parses JSON response","Use argparse for CLI arguments","import json; print(json.dumps(data, indent=2))"],
    expectedConcepts: ["python-modules","python-json","python-functions","python-exceptions"],
    estimatedMinutes: 45,
    xpReward: 60,
  },
  {
    id: "py-blog-cli",
    courseId: "python",
    title: "Blog CLI Tool",
    description: "Build a blog management tool with SQLite — full CRUD, search, and structured data storage.",
    difficulty: 3,
    order: 23,
    learningObjectives: ["Design a SQLite database schema","Execute SQL queries from Python","Build a complete CLI application"],
    requirements: ["Create new blog posts (title, content, tags, date)","List all posts (show title, date, tags)","View a single post by ID","Edit existing posts","Delete posts","Search posts by title or tag"],
    hints: ["import sqlite3; conn = sqlite3.connect('blog.db')","Create table: id, title, content, tags, created_at","Use ? placeholders in SQL to prevent injection","Use argparse for command/subcommand routing"],
    expectedConcepts: ["python-sqlite","python-functions","python-loops","python-datetime"],
    estimatedMinutes: 55,
    xpReward: 70,
  },
  {
    id: "py-chat-server",
    courseId: "python",
    title: "Chat Server",
    description: "Build a multi-client chat server using sockets — networking, threading, and real-time communication.",
    difficulty: 3,
    order: 24,
    learningObjectives: ["Create a TCP server with Python sockets","Handle multiple clients with threading","Broadcast messages to all connected clients"],
    requirements: ["Server accepts multiple client connections","Clients choose a username on connect","Messages broadcast to all connected clients","Server logs all activity","Graceful disconnection handling"],
    hints: ["import socket, threading","Server: socket.socket(), bind(), listen(), accept()","Each client runs in its own thread","Use .encode()/.decode() for string↔bytes"],
    expectedConcepts: ["python-modules","python-threading","python-functions","python-exceptions"],
    estimatedMinutes: 65,
    xpReward: 85,
  },
  {
    id: "py-automation",
    courseId: "python",
    title: "File Organizer (Bonus)",
    description: "Build a tool that automatically organizes files into folders by type — practical automation with the OS module.",
    difficulty: 2,
    order: 25,
    learningObjectives: ["Navigate the file system with os/pathlib","Read and move files programmatically","Build a useful real-world tool"],
    requirements: ["Scan a directory for all files","Categorize files by extension (images, docs, audio, etc.)","Create category folders if they don't exist","Move files into appropriate folders","Report: 'Moved 15 files across 5 categories'"],
    hints: ["import os; os.listdir('path') for files","from pathlib import Path for cleaner paths","Create dict mapping extensions to folders","Use shutil.move(src, dst) to move files"],
    expectedConcepts: ["python-os-module","python-pathlib","python-dictionaries","python-functions","python-exceptions"],
    estimatedMinutes: 40,
    xpReward: 50,
  },
];

export const pythonCourse: Course = {
  id: "python",
  title: "Python",
  fullTitle: "Python — Power and Simplicity",
  description: "Python for everyone. Learn syntax, data structures, OOP, file handling, standard library, async, testing, and essential packages — from zero to production-ready.",
  icon: "Terminal",
  color: "#22c55e",
  difficulty: 2,
  chapters: pythonChapters,
  projects: pythonProjects,
  totalXP: 3936,
  estimatedHours: 87,
};
